export * from './RootLayout/RootLayout';

export * from './HomePage/HomePage';
export * from './UiKitPage/UiKitPage';
export * from './HealingPage/HealingPage';
export * from './GalleryPage/GalleryPage';
export * from './ScientificPublicationsPage/ScientificPublicationsPage';
export * from './FeedbackPage/FeedbackPage';
export * from './PublicationPage/PublicationPage';
export * from './NewsPage/NewsPage';
export * from './NewsDetailPage/NewsDetailPage';
export * from './TrainingDetailPage/TrainingDetailPage';
export * from './ContactsPage/ContactsPage';
export * from './NewsDetailPage/NewsDetailPage';
export * from './AuthorPage/AuthorPage';
export * from './NotFoundPage/NotFoundPage';
export * from './ProcedurePage/ProcedurePage';
export * from './EducationPage/EducationPage';
export * from './ProblemAreasPage/ProblemAreasPage';
